package com.example.common;

public class Constantes {
    public static final String FICHERO = "elementos";
    public static final String FICHEROB = "copiaSeguridad";
    public static final String MENU = "Introduce opción: ";
    public static final String OPCION1 = "1- Listar Diccionario Ordenado";
    public static final String OPCION2 = "2- Insertar un elemento al diccionario";
    public static final String OPCION3 = "3- Modificar algún campo de un elemento del diccionario";
    public static final String OPCION4 = "4- Eliminar un elemento del diccionario";
    public static final String OPCION5 = "5- Salir";
    public static final String CONTRASEÑA_CORRECTA = "Contraseña correcta.";
    public static final String INTRODUZCA_CONTRASEÑA = "Introduzca contraseña.";
    public static final String HA_ELEGIDO_SALIR = "Ha elegido salir.";
    public static final String INTRODUZCA_UNA_OPCIÓN_VÁLIDA = "Introduzca una opción válida";
    public static final String CONTRASEÑA_INCORRECTA = "Contraseña incorrecta.";
    public static final String INTRODUCE_NÚMERO = "Introduce número";
    public static final String TIENES_QUE_INTRODUCIR_UN_NÚMERO_NO_UNA_LETRA = "Tienes que introducir un número, no una letra";
    public static final String INTRODUCE_1_PARA_LISTAR_DE_FORMA_ASCENDENTE_O_2_PARA_DESCENDENTE = "Introduce 1 para listar de forma ascendente o 2 para descendente.";
    public static final String TIENES_QUE_INTRODUCIR_UN_NÚMERO_NO_UNA_LETRA1 = "Tienes que introducir un número, no una letra";
    public static final String INTRODUZCA_EL_ID_DEL_NUEVO_ELEMENTO = "Introduzca el id del nuevo elemento.";
    public static final String INTRODUZCA_EL_NIVEL_DEL_NUEVO_ELEMENTO = "Introduzca el nivel del nuevo elemento.";
    public static final String INTRODUZCA_EL_LA_INCÓGNITA_DEL_NUEVO_ELEMENTO = "Introduzca el la incógnita del nuevo elemento.";
    public static final String INTRODUZCA_LA_CATEGORÍA_DEL_NUEVO_ELEMENTO = "Introduzca la categoría del nuevo elemento.";
    public static final String INTRODUZCA_EL_ID_DEL_ELEMENTO_QUE_DESEA_MODIFICAR = "Introduzca el id del elemento que desea modificar.";
    public static final String INTRODUZCA_1_PARA_MODIFICAR_LA_INCÓGNITA_O_2_PARA_LA_CATEGORÍA = "Introduzca 1 para modificar la incógnita o 2 para la categoría.";
    public static final String INTRODUZCA_LA_NUEVA_INCÓGNITA = "Introduzca la nueva incógnita.";
    public static final String EL_ID_INTRODUCIDO_ES_INCORRECTO = "El id introducido es incorrecto.";
    public static final String MODIFICADA = "Modificada.";
    public static final String INTRODUZCA_LA_NUEVA_CATEGORÍA = "Introduzca la nueva categoría.";
    public static final String EL_ID_O_LA_CATEGORÍA_INTRODUCIDA_ES_INCORRECTA = "El id o la categoría introducida es incorrecta.";
    public static final String MODIFICADA1 = "Modificada.";
    public static final String TIENES_QUE_INTRODUCIR_UN_NÚMERO_NO_UNA_LETRA2 = "Tienes que introducir un número, no una letra";
    public static final String INTRODUZCA_EL_ID_DEL_ELEMENTO_QUE_DESEA_ELIMINAR = "Introduzca el id del elemento que desea eliminar.";
    public static final String ELIMINADA = "Eliminada.";
    public static final String PALABRA_A_ADIVINAR = "Palabra a adivinar:\n";
    public static final String FALLOS = "Fallos:";
    public static final String CORRECTA = "Correcta";
    public static final String INCORRECTA = "Incorrecta";
    public static final String INTRODUZCA_UN_CARACTER_VÁLIDO = "Introduzca un caracter válido.";
    public static final String LA_LETRA_YA_ESTÁ_DICHA = "La letra ya está dicha.";
    public static final String FALLO1 = "  +---+\n  |   |\n      |\n      |\n      |\n      |\n=========";
    public static final String FALLO2 = "  +---+\n  |   |\n  O   |\n      |\n      |\n      |\n=========";
    public static final String FALLO3 = "  +---+\n  |   |\n  O   |\n  |   |\n      |\n      |\n=========";
    public static final String FALLO4 = "  +---+\n  |   |\n  O   |\n /|   |\n      |\n      |\n=========";
    public static final String FALLO5 = "  +---+\n  |   |\n  O   |\n /|\\  |\n      |\n      |\n=========";
    public static final String FALLO6 = "  +---+\n  |   |\n  O   |\n /|\\  |\n /    |\n      |\n=========";
    public static final String FALLO7 = "  +---+\n  |   |\n  O   |\n /|\\  |\n / \\  |\n      |\n=========";
    public static final String INTRODUZCA_0_PARA_EMPEZAR_UNA_NUEVA_PARTIDA_O_1_PARA_RECUPERAR_LA_ANTERIOR = "Introduzca 0 para empezar una nueva partida o 1 para recuperar la anterior.";
    public static final String INTRODUZCA_LETRA = "Introduzca letra.";
    public static final String HAS_PERDIDO_HAS_GASTADO_TODOS_LOS_INTENTOS = "Has perdido, has gastado los intentos.";
    public static final String INTRODUZCA_SU_NOMBRE = "Introduzca su nombre.";
    public static final String INTRODUZCA_DIFICULTAD_0_O_1 = "Introduzca dificultad 0 o 1.";
    public static final String INTRODUZCA_CATEGORÍA = "Introduzca categoría.";
    public static final String INTRODUZCA_1_SI_DESEA_ADMINISTRAR_2_PARA_JUGAR_O_3_PARA_SALIR = "Introduzca 1 si desea administrar, 2 para jugar o 3 para salir.";
    public static final String ENHORABUENA = "Enhorabuena ";
    public static final String HAS_GANADO = ", has ganado!";
}
